---
title: "California Oil Spills"
description: |
  Here is a spatial exploration of oil spills in California 
author:
  - name: Peyton Moore
    url: {}
date: 02-25-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



```{r}
library(tidyverse)
library(sf)
library(janitor)
library(here)
library(tmap)
```

```{r, results='hide'}
#read in data 

counties <- read_sf(here("data", "ca_counties", "CA_Counties", "CA_Counties_TIGER2016.shp")) %>% 
  select(NAME, ALAND) %>% 
  rename(county_name = NAME, land_area = ALAND)

counties %>% 
  st_crs()


oil_spill <- read_sf(here("data", "oil_spill", "Oil_Spill_Incident_Tracking_%5Bds394%5D-shp", "Oil_Spill_Incident_Tracking_%5Bds394%5D.shp" ))

oil_spill %>% 
  st_crs()
```


```{r, results='hide'}
#plot the counties 

# ggplot(data = counties) +
#   geom_sf(aes(fill = land_area), color = "white", size = 0.1) +
#   theme_void() +
#   scale_fill_gradientn(colors = c("cyan","blue","purple"))


#plot the oil spills

# ggplot(data = oil_spill)+
#   geom_sf()+
#   theme_void()

```

###  Interactive tmap of oil spills across California

```{r, include = TRUE}
#map these together

tmap_mode(mode = "view")

tm_shape(counties)+
  tm_borders("darkolivegreen3")+
  tm_shape(oil_spill)+
  tm_dots(alpha = 0.3, col = "darkgoldenrod2", border.col = "darkgoldenrod2", border.alpha = 1)
```

### Chloropath map of total inland oil spills in each county in 2018

```{r, include = TRUE, results='hide'}
# filter out marine oil spills
oil_spill %>% 
  filter(INLANDMARI == "Inland")

#join the oil spill data with the counties data
oil_counties_join <- counties %>% 
  st_join(oil_spill)

# count the number of oil spills in each county 
chloro_oil <- oil_counties_join%>% 
  count(county_name)

# plot these with ggplot 
ggplot(data = chloro_oil) +
  geom_sf(aes(fill = n), color = "white", size = 0.1) +
  scale_fill_gradientn(colors = c("gold","darkorange","firebrick")) +
  theme_void() +
  labs(fill = "Number of Oil Spills", 
       title = "Number of Oil Spills by County in 2008")
```

